export { default as ChromaSection } from "./chromaSection"
export { default as Hero } from "./hero"
export { default as TokenTaxSection } from "./tokenTaxSection"
export { default as SectionWrapper } from "./sectionWrapper"
export { default as InfinityPianoSection } from "./infinityPianoSection"
export { default as MelodySection } from "./melodyMakerSection"
export { default as StockSection } from "./stockSection"
